-- Postgres version of schema.sql (used in production on Neon).
-- IDs are GENERATED BY DEFAULT so the SQLite migration can insert explicit ids.

CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    hash TEXT NOT NULL,
    cash NUMERIC NOT NULL DEFAULT 10000.00
);

CREATE TABLE portfolio (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER REFERENCES users (id),
    symbol TEXT NOT NULL,
    shares INTEGER NOT NULL,
    bought_price DOUBLE PRECISION NOT NULL,
    current_price DOUBLE PRECISION NOT NULL,
    UNIQUE(user_id, symbol)
);

CREATE TABLE snapshots (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users (id),
    date DATE NOT NULL,
    total_value DOUBLE PRECISION NOT NULL,
    UNIQUE(user_id, date)
);

CREATE TABLE history (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER REFERENCES users (id),
    symbol TEXT NOT NULL,
    shares INTEGER NOT NULL,
    method TEXT NOT NULL,
    price DOUBLE PRECISION NOT NULL,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
